// functions/api/random.js
// 这个文件会被 Cloudflare 当作服务端 Worker 执行，不会直接暴露源码

const texts = [
	"Exploring a better way for your lifting projects\n\nDear ,\n\nHope you've been having a great week.\n\nWe’ve been working on a new reinforced sling design that I believe will handle those heavy-duty tasks much more efficiently. I’ve attached a few close-up photos for your take on the build.\n\nLooking forward to hearing what you think.\n\nBest regards,",
	"A quick update on our latest rigging gear\n\nGood day ,\n\nLong time no see, hope everything is running smoothly.\n\nWe just finalized a new model that focuses heavily on edge protection, something we touched upon before. Thought it might be a good fit for your current sites. Pictures are attached for your quick reference.\n\nTalk soon,\n\nBest,",
	"New development that might interest your team\n\nHello ,\n\nHope all is well with your ongoing operations.\n\nI’m reaching out because we’ve just launched a new high-tenacity strap series. It’s significantly lighter but holds the same load capacity, which I thought you might appreciate. Attached the specs and photos here.\n\nLet me know if this looks useful to you.\n\nBest wishes,",
	"Thinking of your recent projects\n\nGreetings ,\n\nI was looking over some notes from our previous chats and wanted to share something new.\n\nWe’ve engineered a new series of slings specifically to solve the wear issues we discussed. I’ve attached a few photos showing the improved texture. Would love to get your expert opinion on this design.\n\nCheers,\n\nBest regards,",
	"A small technical upgrade for your inventory\n\nHi there ,\n\nHope business is treating you well.\n\nWe’ve just finished testing a new product line that offers much better durability in harsh environments. Since you mentioned working on some tough projects, I thought this might be a helpful addition to your gear. Check out the attached photos.\n\nKeep in touch,\n\nBest,",
	"New rigging solution tailored for your needs\n\nHey ,\n\nHope you've been doing great since we last spoke.\n\nWe recently rolled out a new custom-engineered sling series that focuses on better safety margins. I’ve attached the details and a few product photos. Let me know if you’d like to see how it performs in person.\n\nBest wishes,\n\nCheers,",
	"Latest news from our manufacturing team\n\nGood morning ,\n\nHow have things been going on your end?\n\nWe’ve been refining our production process, and I’m excited to share our latest high-strength model with you. It’s built for better longevity and I think it aligns well with your quality standards. Photos attached for you to see.\n\nLooking forward to your thoughts,\n\nBest,",
	"An addition to our lineup you might find useful\n\nDear ,\n\nHope your projects are moving along perfectly.\n\nWe’ve just added a new model to our industrial gear lineup that I personally think is a step up in safety. I’ve attached some photos so you can see the detail. Let me know if you’d like a sample to test.\n\nTalk later,\n\nBest regards,",
	"Product update: More durability for your site\n\nHello ,\n\nHope everything is going well in your corner of the world.\n\nWe’ve just launched a new heavy-duty series that’s specifically designed for longer-term use in the field. I’ve attached the photos to show the material quality. Hope this fits your current requirements.\n\nBest wishes,\n\nCheers,",
	"New gear that might save you some time\n\nGreetings ,\n\nHope you've been having a busy and successful month.\n\nWe’ve developed a new sling type that makes load management much faster. Given your team's focus on efficiency, I thought you might want to take a look. Attached are the photos for your review.\n\nLet me know what you think,\n\nBest,",
	"Just a quick share on our new design\n\nGood day ,\n\nHope all is well with you and your team.\n\nI’m sending over our latest product development as I thought it would be a perfect match for your upcoming site needs. It’s built for maximum reliability. Attached the photos here.\n\nHappy to discuss if you have questions,\n\nBest regards,",
	"A new perspective on industrial lifting\n\nHi there ,\n\nHope you're having a productive week.\n\nWe’ve been working on a new webbing construction that is proving to be much more stable. I’ve attached some photos for your reference, as I value your feedback on these kinds of updates.\n\nTalk soon,\n\nBest wishes,",
	"Improving your current rigging setup\n\nHello ,\n\nHope you’ve been doing well since our last email.\n\nWe’ve just launched a new series designed to tackle the abrasion issues common on most sites. Attached are the photos showing the reinforced sections. Would love to hear if this looks like a good fit for you.\n\nCheers,\n\nBest,",
	"Latest technical update for your reference\n\nHey ,\n\nHope your projects are going smoothly.\n\nWe’ve officially released our new high-performance lifting series. It’s been a long time coming, and I wanted to make sure you were among the first to see the build quality. Photos are attached.\n\nBest regards,\n\nTalk later,",
	"Thought you might like this new development\n\nDear ,\n\nHope you're doing great.\n\nWe’ve just finished a new design that I think really hits the mark on durability. I’ve attached a few photos here for you to check out. Let me know if you think this could be useful for your team.\n\nBest wishes,\n\nCheers,",
	"New product launch: Better safety for your team\n\nGood morning ,\n\nHope everything is going well for you.\n\nWe’ve just released a new line of lifting gear that prioritizes user safety and ease of use. I’ve attached the visuals for your quick review. Let me know if this sparks any interest.\n\nLooking forward to your reply,\n\nBest,",
	"A quick look at our newest model\n\nGreetings ,\n\nHope you've had a successful week.\n\nWe’ve updated our catalog with a new model that I believe outperforms our previous versions in extreme conditions. I’ve attached some photos for you. Hope it proves useful to your operations.\n\nBest regards,\n\nTalk soon,",
	"Technical preview of our latest gear\n\nHello ,\n\nHope all is well on your end.\n\nI wanted to personally share our newest lifting series with you. We’ve focused on better load balance in this version. Attached are the photos. Let me know if this could help with your current projects.\n\nBest wishes,\n\nCheers,",
	"New solutions for your material handling\n\nGood day ,\n\nHope you're having a great month.\n\nWe’ve just launched a new product series that is quite a bit more robust than our standard models. Since you deal with heavy loads often, I thought this was worth sharing. Photos attached.\n\nBest,\n\nTalk later,",
	"Latest progress on our industrial lifting range\n\nHi there ,\n\nHope you’ve been doing well.\n\nWe’ve spent the last few months working on a new design that is finally ready to show. It’s more resilient in harsh weather. I’ve attached some photos for your review.\n\nLet me know your thoughts,\n\nBest regards,",
	"Expanding our rigging options for you\n\nHey ,\n\nHope everything is moving along as planned.\n\nWe’ve just added a new series to our range that is both stronger and more flexible. I’ve attached a few photos so you can see the build quality. Let me know if you have any questions.\n\nCheers,\n\nBest wishes,",
	"A quick note on our newest product\n\nDear ,\n\nHope you're doing fine today.\n\nI’m sharing a new model we just finished—it’s designed to handle complex lifting scenarios more reliably. Attached the images for your reference. Would love to hear if you think this could be useful.\n\nBest,\n\nTalk soon,",
	"Improving the standard for your lifting tasks\n\nHello ,\n\nHope your work is going well.\n\nWe’ve engineered a new sling that really changes the game in terms of longevity. I’ve attached the photos to show you the details. Let me know if this looks like a good match for your team.\n\nBest regards,\n\nCheers,",
	"Check out our latest material handling upgrade\n\nGood morning ,\n\nHope you're having a productive week.\n\nWe’ve developed a new component that makes our lifting gear much easier to manage. I’ve attached the photos for your quick look. Feel free to reach out if you’d like to learn more.\n\nBest wishes,\n\nTalk later,",
	"New design for your heavy-duty projects\n\nGreetings ,\n\nHope all is going well with your team.\n\nWe’ve just launched a new model that’s built for extra endurance. I’ve attached a few photos for you to review. Let me know if this seems like it could help your upcoming work.\n\nBest,\n\nCheers,",
	"Latest development from our engineering team\n\nHi there ,\n\nHope you're doing great today.\n\nI’m reaching out to show you our latest lifting series. We really focused on quality this time, and I’d love to get your thoughts on it. Attached are the photos.\n\nBest regards,\n\nTalk soon,",
	"New and improved: Our latest industrial gear\n\nHey ,\n\nHope business is going well.\n\nWe’ve finalized our new sling series and I wanted to make sure you had a look. It offers much better resistance to wear and tear. I’ve attached the photos for your reference.\n\nBest wishes,\n\nCheers,",
	"A better approach to your lifting needs\n\nGood day ,\n\nHope your projects are on track.\n\nWe just finished a new design that I think you’ll find very interesting. It simplifies the lifting process quite a bit. I’ve attached photos so you can see how it works.\n\nLet me know your feedback,\n\nBest,",
	"Something new that might fit your site\n\nHello ,\n\nHope you're having a great week.\n\nWe’ve just released a new series of straps that are particularly good for tough environments. Attached are the photos for your review. Would love to know if this looks relevant for you.\n\nBest regards,\n\nTalk soon,",
	"Product update for your team\n\nDear ,\n\nHope you're doing well.\n\nWe’ve just added a new series to our product catalog that offers improved strength for high-load tasks. I’ve attached the photos for you to see the improvements. Looking forward to your thoughts.\n\nBest wishes,\n\nCheers,"
  ];

export function onRequest(context) {
    const random = texts[Math.floor(Math.random() * texts.length)];
    
    return new Response(random, {
        headers: {
            "Content-Type": "text/plain;charset=utf-8",
            "Access-Control-Allow-Origin": "*"  // 允许其他网站调用
        }
    });
}