// functions/api/random.js
// 这个文件会被 Cloudflare 当作服务端 Worker 执行，不会直接暴露源码

const texts =[
  "New elegant glassware collection for your kitchenware line\n\nDear ,\n\nHow are you ?\n\nHope you're having a productive week.\n\nWe’ve just launched a new series of kitchen glassware that combines modern aesthetics with high durability. I’ve attached some photos of our latest storage jars and drinking sets. I’d love to hear if these fit your current design focus.\n\nBest regards,",
  "A quick look at our latest crystal-clear drinkware\n\nGood day ,\n\nHow are you ?\n\nHope everything is running smoothly at your office.\n\nWe’ve recently perfected a new line of drinking glasses that are exceptionally clear and chip-resistant. I thought these would be a great addition to your catalog. Images are attached for your quick review.\n\nTalk soon,\n\nBest,",
  "New designs for your glassware inventory\n\nHello ,\n\nHow are you ?\n\nHope all is well with your ongoing operations.\n\nI’m reaching out because we have just introduced a new collection of premium glass storage canisters. They are designed to keep food fresh while looking great on any countertop. Attached are the specs and photos.\n\nLet me know if this looks useful to you.\n\nBest wishes,",
  "Thinking of your kitchenware selection\n\nGreetings ,\n\nHow are you ?\n\nI was reviewing our previous chats and wanted to share our latest glassware developments.\n\nWe’ve engineered a new series of wine glasses that are both elegant and balanced for professional use. I’ve attached a few photos showing the clarity and shape. Would love to get your thoughts on this design.\n\nCheers,\n\nBest regards,",
  "Quality update: Our new durable kitchen glass set\n\nHi there ,\n\nHow are you ?\n\nHope business is treating you well.\n\nWe’ve just finished testing a new line of glass tableware that offers much higher resistance to heat and daily wear. Since you focus on high-quality kitchenware, I thought this would be a perfect fit. Check out the attached photos.\n\nKeep in touch,\n\nBest,",
  "Tailored glassware solutions for your brand\n\nHey ,\n\nHow are you ?\n\nHope you've been doing great since we last spoke.\n\nWe recently rolled out a new custom-glassware range, including versatile storage jars and drinking sets, all focused on a minimalist design. I’ve attached the details and a few product photos. Let me know if you’d like to see samples.\n\nBest wishes,\n\nCheers,",
  "Latest arrivals in our glass drinkware series\n\nGood morning ,\n\nHow are you ?\n\nHow have things been going on your end?\n\nWe’ve been refining our blowing process, and I’m excited to share our latest glassware collection with you. The clarity and weight of these new pieces really stand out. Photos attached for your perusal.\n\nLooking forward to your thoughts,\n\nBest,",
  "New additions to our glassware lineup\n\nDear ,\n\nHow are you ?\n\nHope your projects are moving along perfectly.\n\nWe’ve just added a new model to our glass drinkware range that is both stylish and ergonomic. I’ve attached some photos so you can see the craftsmanship. Let me know if you'd like more details.\n\nTalk later,\n\nBest regards,",
  "Product update: Sleek glass storage canisters\n\nHello ,\n\nHow are you ?\n\nHope everything is going well in your corner of the world.\n\nWe’ve just launched a new series of airtight glass storage jars designed for the modern kitchen. I’ve attached the photos to show the seal quality and aesthetic. Hope this fits your current requirements.\n\nBest wishes,\n\nCheers,",
  "New glassware that might refresh your catalog\n\nGreetings ,\n\nHow are you ?\n\nHope you've been having a busy and successful month.\n\nWe’ve developed a new set of glass wine tumblers that are proving very popular. Given your focus on quality dining ware, I thought you might want to take a look. Attached are the photos for your review.\n\nLet me know what you think,\n\nBest,",
  "Just a quick share on our new glass design\n\nGood day ,\n\nHow are you ?\n\nHope all is well with you and your team.\n\nI’m sending over our latest product development as I thought it would be a perfect match for your kitchenware business. It’s elegant yet functional. Attached the photos here.\n\nHappy to discuss if you have questions,\n\nBest regards,",
  "A new perspective on glass dining ware\n\nHi there ,\n\nHow are you ?\n\nHope you're having a productive week.\n\nWe’ve been working on a new glass composition that is exceptionally bright and smooth. I’ve attached some photos of our newest wine glasses for your reference, as I value your feedback on these updates.\n\nTalk soon,\n\nBest wishes,",
  "Improving your current glass drinkware setup\n\nHello ,\n\nHow are you ?\n\nHope you’ve been doing well since our last email.\n\nWe’ve just launched a new series of glassware designed to handle daily dishwasher use without clouding. Attached are the photos showing the quality. Would love to hear if this looks like a good fit for you.\n\nCheers,\n\nBest,",
  "Latest technical update on our glassware\n\nHey ,\n\nHow are you ?\n\nHope your projects are going smoothly.\n\nWe’ve officially released our new high-transparency drinkware series. It’s been a long time coming, and I wanted to make sure you were among the first to see the finished pieces. Photos are attached.\n\nBest regards,\n\nTalk later,",
  "Thought you might like our new glass collection\n\nDear ,\n\nHow are you ?\n\nHope you're doing great.\n\nWe’ve just finished a new design for glass storage jars that really hits the mark on both form and function. I’ve attached a few photos here for you to check out. Let me know if you think this could be useful for your team.\n\nBest wishes,\n\nCheers,",
  "New product launch: Stylish glass sets for kitchen\n\nGood morning ,\n\nHow are you ?\n\nHope everything is going well for you.\n\nWe’ve just released a new line of glass kitchenware that balances affordability with luxury. I’ve attached the visuals for your quick review. Let me know if this sparks any interest.\n\nLooking forward to your reply,\n\nBest,",
  "A quick look at our newest glassware\n\nGreetings ,\n\nHow are you ?\n\nHope you've had a successful week.\n\nWe’ve updated our catalog with new glass drinking sets that I believe outperform our previous versions in elegance. I’ve attached some photos for you. Hope it proves useful to your operations.\n\nBest regards,\n\nTalk soon,",
  "Technical preview of our latest glass series\n\nHello ,\n\nHow are you ?\n\nHope all is well on your end.\n\nI wanted to personally share our newest glassware series with you. We’ve focused on better grip and balance in this version. Attached are the photos. Let me know if this could help with your current selection.\n\nBest wishes,\n\nCheers,",
  "New solutions for your kitchen storage\n\nGood day ,\n\nHow are you ?\n\nHope you're having a great month.\n\nWe’ve just launched a new series of glass canisters that are quite a bit more durable than our standard models. Since you deal with kitchenware often, I thought this was worth sharing. Photos attached.\n\nBest,\n\nTalk later,",
  "Latest progress on our glass drinkware range\n\nHi there ,\n\nHow are you ?\n\nHope you’ve been doing well.\n\nWe’ve spent the last few months working on a new glass design that is finally ready to show. It’s more resilient in daily use. I’ve attached some photos for your review.\n\nLet me know your thoughts,\n\nBest regards,",
  "Expanding our kitchen glassware options for you\n\nHey ,\n\nHow are you ?\n\nHope everything is moving along as planned.\n\nWe’ve just added a new series to our range that is both elegant and versatile for dining. I’ve attached a few photos so you can see the build quality. Let me know if you have any questions.\n\nCheers,\n\nBest wishes,",
  "A quick note on our newest glass product\n\nDear ,\n\nHow are you ?\n\nHope you're doing fine today.\n\nI’m sharing a new wine glass model we just finished—it’s designed to enhance the drinking experience. Attached the images for your reference. Would love to hear if you think this could be useful.\n\nBest,\n\nTalk soon,",
  "Improving the standard for your glass collection\n\nHello ,\n\nHow are you ?\n\nHope your work is going well.\n\nWe’ve engineered a new glass jar that really changes the game in terms of clarity. I’ve attached the photos to show you the details. Let me know if this looks like a good match for your team.\n\nBest regards,\n\nCheers,",
  "Check out our latest kitchen glassware upgrade\n\nGood morning ,\n\nHow are you ?\n\nHope you're having a productive week.\n\nWe’ve developed a new lid-seal component that makes our glass storage jars much more practical. I’ve attached the photos for your quick look. Feel free to reach out if you’d like to learn more.\n\nBest wishes,\n\nTalk later,",
  "New glass designs for your kitchenware projects\n\nGreetings ,\n\nHow are you ?\n\nHope all is going well with your team.\n\nWe’ve just launched a new model of glass drinking cups built for extra durability. I’ve attached a few photos for you to review. Let me know if this seems like it could help your upcoming work.\n\nBest,\n\nCheers,",
  "Latest development from our glass studio\n\nHi there ,\n\nHow are you ?\n\nHope you're doing great today.\n\nI’m reaching out to show you our latest kitchen glass collection. We really focused on the aesthetic finish this time, and I’d love to get your thoughts on it. Attached are the photos.\n\nBest regards,\n\nTalk soon,",
  "New and improved: Our latest glass drinkware\n\nHey ,\n\nHow are you ?\n\nHope business is going well.\n\nWe’ve finalized our new glassware series and I wanted to make sure you had a look. It offers much better resistance to scratching and clouding. I’ve attached the photos for your reference.\n\nBest wishes,\n\nCheers,",
  "A better approach to your glassware needs\n\nGood day ,\n\nHow are you ?\n\nHope your projects are on track.\n\nWe just finished a new wine glass design that I think you’ll find very interesting. It simplifies the dining table setup quite a bit. I’ve attached photos so you can see how it looks.\n\nLet me know your feedback,\n\nBest,",
  "Something new that might fit your kitchenware store\n\nHello ,\n\nHow are you ?\n\nHope you're having a great week.\n\nWe’ve just released a new series of glass food jars that are particularly good for pantry organization. Attached are the photos for your review. Would love to know if this looks relevant for you.\n\nBest regards,\n\nTalk soon,",
  "Product update for your glass catalog\n\nDear ,\n\nHow are you ?\n\nHope you're doing well.\n\nWe’ve just added a new series to our product catalog that offers improved clarity and design for high-end dining. I’ve attached the photos for you to see the improvements. Looking forward to your thoughts.\n\nBest wishes,\n\nCheers,"
];

export function onRequest(context) {
    const random = texts[Math.floor(Math.random() * texts.length)];
    
    return new Response(random, {
        headers: {
            "Content-Type": "text/plain;charset=utf-8",
            "Access-Control-Allow-Origin": "*"  // 允许其他网站调用
        }
    });
}